version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: hotel_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  web:
    build: .  # Path to your Flask app (Dockerfile should be here)
    container_name: hotel_flask
    restart: unless-stopped
    ports:
      - "5000:5000"  # Access Flask app in browser at localhost:5000
    depends_on:
      - db
    environment:
      - FLASK_ENV=development

volumes:
  mysql-data:
