apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kaniko-agent
    jenkins: agent  # Matches Jenkins pod label (jenkins: agent)
spec:
  serviceAccountName: jenkins
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: Always
      command:
        - /kaniko/executor
      args:
        - --dockerfile=/workspace/Dockerfile
        - --context=dir:///workspace/
        - --destination=docker.io/samir3112/hotel-management:latest
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: regcred
