apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotel-app
  template:
    metadata:
      labels:
        app: hotel-app
    spec:
      containers:
      - name: hotel-container
        image: samir3112/hotel-management:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
