apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          emptyDir: {}


#  kubectl apply -f k8s/jenkins-deployment.yaml
#  kubectl apply -f k8s/jenkins-service.yaml
#  kubectl get pods
# kubectl describe pod jenkins-55c7c9548d-ffb8v
# kubectl exec -it jenkins-55c7c9548d-ffb8v -- /bin/bash
# cat /var/jenkins_home/secrets/initialAdminPassword