apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: samir3112/jenkins-container:v1
          ports:
            - containerPort: 8080
            - containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-pvc



 #  mkdir -p ~/.docker  docker login -u samir3112 -p NilSam@3112  (login credentials by kaniko)
  # kubectl delete secret dockerhub-secret (if new added)
  # kubectl create secret generic dockerhub-secret \
  # --from-file=.dockerconfigjson=/home/vagrant/.docker/config.json \
  # --type=kubernetes.io/dockerconfigjson

  # kubectl apply -f jenkins-pv.yaml
  # kubectl apply -f jenkins-pvc.yaml
  # kubectl apply -f jenkins-deployment.yaml
  # kubectl apply -f jenkins-service.yaml
  # kubectl get pods
  #  kubectl get svc
  #  kubectl describe pod <--pod name-->