apiVersion: v1
kind: Pod
metadata:
  name: kaniko-agent
  labels:
    jenkins/label: kaniko
spec:
  serviceAccountName: kaniko-sa
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      # No command needed
      args: ["--help"]  # Just makes the container run and exit cleanly
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
  volumes:
    - name: docker-config
      secret:
        secretName: regcred
