apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
  name: kaniko-agent
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/Dockerfile",
           "--context=dir://workspace/",
           "--destination=samir3112/hotel-management:latest",
           "--verbosity=info"]
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
  - name: docker-config
    secret:
      secretName: dockerhub-secret
