apiVersion: v1
kind: Pod
metadata:
  name: kaniko-agent
  labels:
    some-label: kaniko-agent
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      command:
        - /busybox/cat
      tty: true
      volumeMounts:
        - name: docker-config
          mountPath: /kaniko/.docker
        - name: kaniko-secret
          mountPath: /secret
  volumes:
    - name: docker-config
      emptyDir: {}
    - name: kaniko-secret
      secret:
        secretName: dockerhub-secret
  restartPolicy: Never
