apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko-sa
  namespace: default    # <--- changed to default namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko-role
  namespace: default    # <--- changed to default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/exec"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko-rolebinding
  namespace: default    # <--- changed to default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaniko-role
subjects:
  - kind: ServiceAccount
    name: kaniko-sa
    namespace: default    # <--- changed to default
